rel_paths:
  test_data_root: "test/data/"
  models_root: "data/models/"
  raw_data_root: "data/raw/"
  cleansed_data_root: "data/cleansed/"
  interim_debug_root: "data/interim/"

generate_raw_names:
  output_filename: "individuals_generated.csv"
  name_count: 20

cleanse_and_tokenize:
  output_filename: "train_test.pickle"
  businesses_filename: "linkedin_company_names.csv"
  individuals_filename: "imdb_names.csv"
  tokenized_length: 120
  encoding_space_size: 200

train_model:
  best_model_filename: "best_model.h5"
  secondary_model_filename: "dev_only_secondary_model.h5"
  history_filename: "dev_only_history.pickle"
  embedding_size: 128
  batch_size: 16384
  epochs: 30
  validation_split: 0.1






